version: '3.8'

services:

  db-gateway-service:
    build:
      context: ./services/db-gateway-service
      dockerfile: Dockerfile
    container_name: db-gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env/mysql.env
      - .env/pg.env
      - .env/redis.env
    depends_on:
      - mysql
      - postgres
      - redis
    networks:
      - microcloud-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microcloud-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env/pg.env
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microcloud-net

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env/redis.env
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microcloud-net

networks:
  microcloud-net:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
